name: 'Terraform Infra Provisioning'

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_project_id: ${{ secrets.PROJECT_ID }}
      TF_VAR_region: ${{ secrets.REGION }}
      TF_VAR_zone: ${{ secrets.ZONE }}
      TF_VAR_cluster_name: ${{ secrets.CLUSTER_NAME }}
      TF_VAR_network_name: ${{ secrets.NETWORK_NAME }}
      TF_VAR_subnetwork_name: ${{ secrets.SUBNETWORK_NAME }}
      TF_VAR_ip_cidr_range: ${{ secrets.IP_CIDR_RANGE }}
      TF_VAR_node_count: ${{ secrets.NODE_COUNT }}
      TF_VAR_machine_type: ${{ secrets.MACHINE_TYPE }}
      TF_VAR_disk_type: ${{ secrets.DISK_TYPE }}
      TF_VAR_disk_size_gb: ${{ secrets.DISK_SIZE_GB }}
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to GCP
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.4

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="bucket=${{ secrets.TF_BUCKET }}"


    - name: Terraform Planning
      run: terraform plan -out=tfplan.binary

    - name: Upload Terraform Plan Output
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-output
        path: tfplan.binary

    - name: Terraform Apply
      run: terraform apply -auto-approve
